# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/wasuaje/Documentos/desarrollo/nomina/ui/empleados.ui'
#
# Created: Thu Jul 14 14:34:42 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(465, 457)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(500, 1000))
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 461, 411))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frmbotonera = QtGui.QFrame(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmbotonera.sizePolicy().hasHeightForWidth())
        self.frmbotonera.setSizePolicy(sizePolicy)
        self.frmbotonera.setMinimumSize(QtCore.QSize(50, 40))
        self.frmbotonera.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmbotonera.setFrameShadow(QtGui.QFrame.Raised)
        self.frmbotonera.setObjectName(_fromUtf8("frmbotonera"))
        self.verticalLayout.addWidget(self.frmbotonera)
        spacerItem = QtGui.QSpacerItem(2, 2, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget = QtGui.QTabWidget(self.layoutWidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.frame_2 = QtGui.QFrame(self.tab)
        self.frame_2.setEnabled(False)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 441, 301))
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.widget = QtGui.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(230, 10, 70, 151))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_24 = QtGui.QLabel(self.widget)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout_3.addWidget(self.label_24)
        self.label_22 = QtGui.QLabel(self.widget)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_3.addWidget(self.label_22)
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_3.addWidget(self.label_10)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_26 = QtGui.QLabel(self.widget)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout_3.addWidget(self.label_26)
        self.widget1 = QtGui.QWidget(self.frame_2)
        self.widget1.setGeometry(QtCore.QRect(90, 6, 131, 161))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lncodigo = QtGui.QLineEdit(self.widget1)
        self.lncodigo.setObjectName(_fromUtf8("lncodigo"))
        self.verticalLayout_4.addWidget(self.lncodigo)
        self.lnnombres = QtGui.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lnnombres.setFont(font)
        self.lnnombres.setObjectName(_fromUtf8("lnnombres"))
        self.verticalLayout_4.addWidget(self.lnnombres)
        self.lncedula = QtGui.QLineEdit(self.widget1)
        self.lncedula.setObjectName(_fromUtf8("lncedula"))
        self.verticalLayout_4.addWidget(self.lncedula)
        self.lntlfhab = QtGui.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lntlfhab.setFont(font)
        self.lntlfhab.setObjectName(_fromUtf8("lntlfhab"))
        self.verticalLayout_4.addWidget(self.lntlfhab)
        self.lnfecnac = QtGui.QDateEdit(self.widget1)
        self.lnfecnac.setDate(QtCore.QDate(1900, 1, 1))
        self.lnfecnac.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(7999, 12, 28), QtCore.QTime(23, 59, 59)))
        self.lnfecnac.setCalendarPopup(True)
        self.lnfecnac.setObjectName(_fromUtf8("lnfecnac"))
        self.verticalLayout_4.addWidget(self.lnfecnac)
        self.widget2 = QtGui.QWidget(self.frame_2)
        self.widget2.setGeometry(QtCore.QRect(310, 10, 121, 161))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget2)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.lnsexo = QtGui.QLineEdit(self.widget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnsexo.sizePolicy().hasHeightForWidth())
        self.lnsexo.setSizePolicy(sizePolicy)
        self.lnsexo.setMinimumSize(QtCore.QSize(5, 5))
        self.lnsexo.setMaximumSize(QtCore.QSize(30, 25))
        self.lnsexo.setText(_fromUtf8(""))
        self.lnsexo.setObjectName(_fromUtf8("lnsexo"))
        self.verticalLayout_5.addWidget(self.lnsexo)
        self.lnapellidos = QtGui.QLineEdit(self.widget2)
        self.lnapellidos.setObjectName(_fromUtf8("lnapellidos"))
        self.verticalLayout_5.addWidget(self.lnapellidos)
        self.lnrif = QtGui.QLineEdit(self.widget2)
        self.lnrif.setObjectName(_fromUtf8("lnrif"))
        self.verticalLayout_5.addWidget(self.lnrif)
        self.lntlfcel = QtGui.QLineEdit(self.widget2)
        self.lntlfcel.setObjectName(_fromUtf8("lntlfcel"))
        self.verticalLayout_5.addWidget(self.lntlfcel)
        self.lncodigo_3 = QtGui.QLineEdit(self.widget2)
        self.lncodigo_3.setEnabled(False)
        self.lncodigo_3.setText(_fromUtf8(""))
        self.lncodigo_3.setObjectName(_fromUtf8("lncodigo_3"))
        self.verticalLayout_5.addWidget(self.lncodigo_3)
        self.widget3 = QtGui.QWidget(self.frame_2)
        self.widget3.setGeometry(QtCore.QRect(11, 0, 69, 171))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget3)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.widget3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_23 = QtGui.QLabel(self.widget3)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_2.addWidget(self.label_23)
        self.label_3 = QtGui.QLabel(self.widget3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_7 = QtGui.QLabel(self.widget3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_25 = QtGui.QLabel(self.widget3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout_2.addWidget(self.label_25)
        self.widget4 = QtGui.QWidget(self.frame_2)
        self.widget4.setGeometry(QtCore.QRect(11, 175, 77, 121))
        self.widget4.setObjectName(_fromUtf8("widget4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget4)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_6 = QtGui.QLabel(self.widget4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_6.addWidget(self.label_6)
        self.label_8 = QtGui.QLabel(self.widget4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_6.addWidget(self.label_8)
        self.label_11 = QtGui.QLabel(self.widget4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_6.addWidget(self.label_11)
        self.widget5 = QtGui.QWidget(self.frame_2)
        self.widget5.setGeometry(QtCore.QRect(90, 170, 341, 121))
        self.widget5.setObjectName(_fromUtf8("widget5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget5)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.txtdir1 = QtGui.QPlainTextEdit(self.widget5)
        self.txtdir1.setObjectName(_fromUtf8("txtdir1"))
        self.verticalLayout_7.addWidget(self.txtdir1)
        self.txtdir2 = QtGui.QPlainTextEdit(self.widget5)
        self.txtdir2.setObjectName(_fromUtf8("txtdir2"))
        self.verticalLayout_7.addWidget(self.txtdir2)
        self.lnemail = QtGui.QLineEdit(self.widget5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lnemail.setFont(font)
        self.lnemail.setObjectName(_fromUtf8("lnemail"))
        self.verticalLayout_7.addWidget(self.lnemail)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.frame_3 = QtGui.QFrame(self.tab_3)
        self.frame_3.setEnabled(False)
        self.frame_3.setGeometry(QtCore.QRect(10, 0, 421, 311))
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.widget6 = QtGui.QWidget(self.frame_3)
        self.widget6.setGeometry(QtCore.QRect(50, 20, 321, 281))
        self.widget6.setObjectName(_fromUtf8("widget6"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget6)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_9 = QtGui.QLabel(self.widget6)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_8.addWidget(self.label_9)
        self.label_4 = QtGui.QLabel(self.widget6)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_8.addWidget(self.label_4)
        self.label_27 = QtGui.QLabel(self.widget6)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout_8.addWidget(self.label_27)
        self.label_12 = QtGui.QLabel(self.widget6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_8.addWidget(self.label_12)
        self.label_14 = QtGui.QLabel(self.widget6)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_8.addWidget(self.label_14)
        self.label_13 = QtGui.QLabel(self.widget6)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_8.addWidget(self.label_13)
        self.label_15 = QtGui.QLabel(self.widget6)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_8.addWidget(self.label_15)
        self.label_21 = QtGui.QLabel(self.widget6)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_8.addWidget(self.label_21)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.lnfecingreso = QtGui.QDateEdit(self.widget6)
        self.lnfecingreso.setDate(QtCore.QDate(1900, 1, 1))
        self.lnfecingreso.setObjectName(_fromUtf8("lnfecingreso"))
        self.verticalLayout_9.addWidget(self.lnfecingreso)
        self.cmbtipemp = QtGui.QComboBox(self.widget6)
        self.cmbtipemp.setObjectName(_fromUtf8("cmbtipemp"))
        self.verticalLayout_9.addWidget(self.cmbtipemp)
        self.cmbdpto = QtGui.QComboBox(self.widget6)
        self.cmbdpto.setObjectName(_fromUtf8("cmbdpto"))
        self.verticalLayout_9.addWidget(self.cmbdpto)
        self.cmbcargo = QtGui.QComboBox(self.widget6)
        self.cmbcargo.setObjectName(_fromUtf8("cmbcargo"))
        self.verticalLayout_9.addWidget(self.cmbcargo)
        self.cmbtipnom = QtGui.QComboBox(self.widget6)
        self.cmbtipnom.setObjectName(_fromUtf8("cmbtipnom"))
        self.verticalLayout_9.addWidget(self.cmbtipnom)
        self.cmbbanco = QtGui.QComboBox(self.widget6)
        self.cmbbanco.setObjectName(_fromUtf8("cmbbanco"))
        self.verticalLayout_9.addWidget(self.cmbbanco)
        self.lncuenta = QtGui.QLineEdit(self.widget6)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lncuenta.setFont(font)
        self.lncuenta.setObjectName(_fromUtf8("lncuenta"))
        self.verticalLayout_9.addWidget(self.lncuenta)
        self.lnfecegreso = QtGui.QDateEdit(self.widget6)
        self.lnfecegreso.setDate(QtCore.QDate(1900, 1, 1))
        self.lnfecegreso.setObjectName(_fromUtf8("lnfecegreso"))
        self.verticalLayout_9.addWidget(self.lnfecegreso)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.frame_4 = QtGui.QFrame(self.tab_4)
        self.frame_4.setEnabled(False)
        self.frame_4.setGeometry(QtCore.QRect(0, 10, 431, 301))
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.pushDel = QtGui.QPushButton(self.frame_4)
        self.pushDel.setEnabled(False)
        self.pushDel.setGeometry(QtCore.QRect(390, 140, 31, 27))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos2/img2/cross.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushDel.setIcon(icon)
        self.pushDel.setFlat(True)
        self.pushDel.setObjectName(_fromUtf8("pushDel"))
        self.label_19 = QtGui.QLabel(self.frame_4)
        self.label_19.setGeometry(QtCore.QRect(350, 20, 41, 20))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.lnssem = QtGui.QLineEdit(self.frame_4)
        self.lnssem.setEnabled(False)
        self.lnssem.setGeometry(QtCore.QRect(230, 40, 91, 27))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lnssem.setFont(font)
        self.lnssem.setText(_fromUtf8(""))
        self.lnssem.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lnssem.setObjectName(_fromUtf8("lnssem"))
        self.label_20 = QtGui.QLabel(self.frame_4)
        self.label_20.setGeometry(QtCore.QRect(10, 80, 91, 20))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.lnfecsueldo = QtGui.QDateEdit(self.frame_4)
        self.lnfecsueldo.setGeometry(QtCore.QRect(110, 80, 110, 27))
        self.lnfecsueldo.setObjectName(_fromUtf8("lnfecsueldo"))
        self.pushAdd = QtGui.QPushButton(self.frame_4)
        self.pushAdd.setGeometry(QtCore.QRect(390, 110, 31, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos2/img2/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushAdd.setIcon(icon1)
        self.pushAdd.setFlat(True)
        self.pushAdd.setObjectName(_fromUtf8("pushAdd"))
        self.label_17 = QtGui.QLabel(self.frame_4)
        self.label_17.setGeometry(QtCore.QRect(140, 20, 61, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.lnsmen = QtGui.QLineEdit(self.frame_4)
        self.lnsmen.setGeometry(QtCore.QRect(110, 40, 111, 27))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lnsmen.setFont(font)
        self.lnsmen.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lnsmen.setObjectName(_fromUtf8("lnsmen"))
        self.label_18 = QtGui.QLabel(self.frame_4)
        self.label_18.setGeometry(QtCore.QRect(250, 20, 61, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_16 = QtGui.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(10, 40, 61, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.tableView = QtGui.QTableView(self.frame_4)
        self.tableView.setGeometry(QtCore.QRect(10, 111, 361, 181))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.lnsdiario = QtGui.QLineEdit(self.frame_4)
        self.lnsdiario.setEnabled(False)
        self.lnsdiario.setGeometry(QtCore.QRect(330, 40, 91, 27))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lnsdiario.setFont(font)
        self.lnsdiario.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lnsdiario.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lnsdiario.setObjectName(_fromUtf8("lnsdiario"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.frame_5 = QtGui.QFrame(self.tab_2)
        self.frame_5.setEnabled(False)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 431, 311))
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.btnfoto = QtGui.QPushButton(self.frame_5)
        self.btnfoto.setGeometry(QtCore.QRect(290, 280, 31, 27))
        self.btnfoto.setObjectName(_fromUtf8("btnfoto"))
        self.frame = QtGui.QFrame(self.frame_5)
        self.frame.setGeometry(QtCore.QRect(100, 30, 231, 231))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.lblfoto = QtGui.QLabel(self.frame)
        self.lblfoto.setGeometry(QtCore.QRect(10, 10, 211, 211))
        self.lblfoto.setScaledContents(True)
        self.lblfoto.setAlignment(QtCore.Qt.AlignCenter)
        self.lblfoto.setObjectName(_fromUtf8("lblfoto"))
        self.lnfoto = QtGui.QLineEdit(self.frame_5)
        self.lnfoto.setEnabled(False)
        self.lnfoto.setGeometry(QtCore.QRect(100, 280, 161, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lnfoto.setFont(font)
        self.lnfoto.setObjectName(_fromUtf8("lnfoto"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 465, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuNuevo = QtGui.QMenu(self.menuBar)
        self.menuNuevo.setObjectName(_fromUtf8("menuNuevo"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionNuevo = QtGui.QAction(MainWindow)
        self.actionNuevo.setObjectName(_fromUtf8("actionNuevo"))
        self.actionModificar = QtGui.QAction(MainWindow)
        self.actionModificar.setObjectName(_fromUtf8("actionModificar"))
        self.actionEliminar = QtGui.QAction(MainWindow)
        self.actionEliminar.setObjectName(_fromUtf8("actionEliminar"))
        self.actionGuardar = QtGui.QAction(MainWindow)
        self.actionGuardar.setObjectName(_fromUtf8("actionGuardar"))
        self.actionSalir = QtGui.QAction(MainWindow)
        self.actionSalir.setObjectName(_fromUtf8("actionSalir"))
        self.menuNuevo.addAction(self.actionNuevo)
        self.menuNuevo.addAction(self.actionModificar)
        self.menuNuevo.addAction(self.actionGuardar)
        self.menuNuevo.addAction(self.actionEliminar)
        self.menuNuevo.addSeparator()
        self.menuNuevo.addAction(self.actionSalir)
        self.menuBar.addAction(self.menuNuevo.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lncodigo, self.lnsexo)
        MainWindow.setTabOrder(self.lnsexo, self.lnnombres)
        MainWindow.setTabOrder(self.lnnombres, self.lnapellidos)
        MainWindow.setTabOrder(self.lnapellidos, self.lncedula)
        MainWindow.setTabOrder(self.lncedula, self.lnrif)
        MainWindow.setTabOrder(self.lnrif, self.lntlfhab)
        MainWindow.setTabOrder(self.lntlfhab, self.lntlfcel)
        MainWindow.setTabOrder(self.lntlfcel, self.lncodigo_3)
        MainWindow.setTabOrder(self.lncodigo_3, self.txtdir1)
        MainWindow.setTabOrder(self.txtdir1, self.txtdir2)
        MainWindow.setTabOrder(self.txtdir2, self.lnemail)
        MainWindow.setTabOrder(self.lnemail, self.cmbtipemp)
        MainWindow.setTabOrder(self.cmbtipemp, self.cmbdpto)
        MainWindow.setTabOrder(self.cmbdpto, self.cmbcargo)
        MainWindow.setTabOrder(self.cmbcargo, self.cmbtipnom)
        MainWindow.setTabOrder(self.cmbtipnom, self.cmbbanco)
        MainWindow.setTabOrder(self.cmbbanco, self.lncuenta)
        MainWindow.setTabOrder(self.lncuenta, self.lnsmen)
        MainWindow.setTabOrder(self.lnsmen, self.lnssem)
        MainWindow.setTabOrder(self.lnssem, self.lnsdiario)
        MainWindow.setTabOrder(self.lnsdiario, self.pushAdd)
        MainWindow.setTabOrder(self.pushAdd, self.pushDel)
        MainWindow.setTabOrder(self.pushDel, self.lnfoto)
        MainWindow.setTabOrder(self.lnfoto, self.btnfoto)
        MainWindow.setTabOrder(self.btnfoto, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.tableView)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Empleados", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Sexo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Apellidos:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Rif.:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Tlf. Cel.:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Edad:", None, QtGui.QApplication.UnicodeUTF8))
        self.lnfecnac.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.lnsexo.setInputMask(QtGui.QApplication.translate("MainWindow", ">A; ", None, QtGui.QApplication.UnicodeUTF8))
        self.lnrif.setInputMask(QtGui.QApplication.translate("MainWindow", "A-99999999-9; ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Codigo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Nombres:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Cedula:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Tlf. Hab.:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Fec. Nac.:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Direccion1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Direccion2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "E-mail.:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Personales", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Fecha Ingreso:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Tipo de Empleado:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Departamento:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Cargo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Tipo de Nomina:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Banco p/Nomina:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Cuenta nomina:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Fecha de Egreso:", None, QtGui.QApplication.UnicodeUTF8))
        self.lnfecingreso.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.lnfecegreso.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Nomina", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Diario", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Desde Fecha:", None, QtGui.QApplication.UnicodeUTF8))
        self.lnfecsueldo.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Mensual", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Semanal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Sueldo:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Sueldo/Salario", None, QtGui.QApplication.UnicodeUTF8))
        self.btnfoto.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblfoto.setText(QtGui.QApplication.translate("MainWindow", "FOTO", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Foto", None, QtGui.QApplication.UnicodeUTF8))
        self.menuNuevo.setTitle(QtGui.QApplication.translate("MainWindow", "&Archivo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevo.setText(QtGui.QApplication.translate("MainWindow", "Nuevo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModificar.setText(QtGui.QApplication.translate("MainWindow", "Modificar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEliminar.setText(QtGui.QApplication.translate("MainWindow", "Eliminar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGuardar.setText(QtGui.QApplication.translate("MainWindow", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalir.setText(QtGui.QApplication.translate("MainWindow", "Salir", None, QtGui.QApplication.UnicodeUTF8))

import recurso_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

